version: 2
models:
- name: adwords_ad_performance_xf
  columns:
  - name: id
    tests:
    - not_null
    - unique
- name: adwords_campaign_performance_xf
  columns:
  - name: id
    tests:
    - not_null
    - unique
- name: adwords_click_performance
  columns:
  - name: id
    tests:
    - not_null
    - unique
